/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MarketsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MarketsApiTests : IDisposable
    {
        private MarketsApi instance;

        public MarketsApiTests()
        {
            instance = new MarketsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MarketsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MarketsApi
            //Assert.IsType(typeof(MarketsApi), instance, "instance is a MarketsApi");
        }

        
        /// <summary>
        /// Test ApiMarketsCurrenciesGet
        /// </summary>
        [Fact]
        public void ApiMarketsCurrenciesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiMarketsCurrenciesGet();
            //Assert.IsType<List<Object>> (response, "response is List<Object>");
        }
        
        /// <summary>
        /// Test ApiMarketsGet
        /// </summary>
        [Fact]
        public void ApiMarketsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fingerprint = null;
            //var response = instance.ApiMarketsGet(fingerprint);
            //Assert.IsType<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ApiMarketsHistoryGet
        /// </summary>
        [Fact]
        public void ApiMarketsHistoryGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string pair = null;
            //var response = instance.ApiMarketsHistoryGet(pair);
            //Assert.IsType<List<Object>> (response, "response is List<Object>");
        }
        
        /// <summary>
        /// Test ApiMarketsOrderbookGet
        /// </summary>
        [Fact]
        public void ApiMarketsOrderbookGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string pair = null;
            //instance.ApiMarketsOrderbookGet(pair);
            
        }
        
        /// <summary>
        /// Test ApiMarketsTickersGet
        /// </summary>
        [Fact]
        public void ApiMarketsTickersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiMarketsTickersGet();
            //Assert.IsType<Object> (response, "response is Object");
        }
        
    }

}
