/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StaticPagesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StaticPagesApiTests : IDisposable
    {
        private StaticPagesApi instance;

        public StaticPagesApiTests()
        {
            instance = new StaticPagesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StaticPagesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StaticPagesApi
            //Assert.IsType(typeof(StaticPagesApi), instance, "instance is a StaticPagesApi");
        }

        
        /// <summary>
        /// Test StaticPagesAffiliateGet
        /// </summary>
        [Fact]
        public void StaticPagesAffiliateGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.StaticPagesAffiliateGet();
            
        }
        
        /// <summary>
        /// Test StaticPagesStatusGet
        /// </summary>
        [Fact]
        public void StaticPagesStatusGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.StaticPagesStatusGet();
            
        }
        
    }

}
