/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Trade
    /// </summary>
    [DataContract]
    public partial class Trade :  IEquatable<Trade>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets TradeType
        /// </summary>
        [DataMember(Name="tradeType", EmitDefaultValue=false)]
        public TradeType? TradeType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Trade" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="pairId">pairId.</param>
        /// <param name="makerOrderId">makerOrderId.</param>
        /// <param name="takerOrderId">takerOrderId.</param>
        /// <param name="price">price.</param>
        /// <param name="amount">amount.</param>
        /// <param name="total">total.</param>
        /// <param name="transactionDate">transactionDate.</param>
        /// <param name="tradeType">tradeType.</param>
        public Trade(string id = default(string), string pairId = default(string), string makerOrderId = default(string), string takerOrderId = default(string), double price = default(double), double amount = default(double), double total = default(double), long transactionDate = default(long), TradeType? tradeType = default(TradeType?))
        {
            this.Id = id;
            this.PairId = pairId;
            this.MakerOrderId = makerOrderId;
            this.TakerOrderId = takerOrderId;
            this.Price = price;
            this.Amount = amount;
            this.Total = total;
            this.TransactionDate = transactionDate;
            this.TradeType = tradeType;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets PairId
        /// </summary>
        [DataMember(Name="pairId", EmitDefaultValue=true)]
        public string PairId { get; set; }

        /// <summary>
        /// Gets or Sets MakerOrderId
        /// </summary>
        [DataMember(Name="makerOrderId", EmitDefaultValue=true)]
        public string MakerOrderId { get; set; }

        /// <summary>
        /// Gets or Sets TakerOrderId
        /// </summary>
        [DataMember(Name="takerOrderId", EmitDefaultValue=true)]
        public string TakerOrderId { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name="price", EmitDefaultValue=false)]
        public double Price { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public double Amount { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name="total", EmitDefaultValue=false)]
        public double Total { get; set; }

        /// <summary>
        /// Gets or Sets TransactionDate
        /// </summary>
        [DataMember(Name="transactionDate", EmitDefaultValue=false)]
        public long TransactionDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Trade {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PairId: ").Append(PairId).Append("\n");
            sb.Append("  MakerOrderId: ").Append(MakerOrderId).Append("\n");
            sb.Append("  TakerOrderId: ").Append(TakerOrderId).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  TransactionDate: ").Append(TransactionDate).Append("\n");
            sb.Append("  TradeType: ").Append(TradeType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Trade);
        }

        /// <summary>
        /// Returns true if Trade instances are equal
        /// </summary>
        /// <param name="input">Instance of Trade to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Trade input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.PairId == input.PairId ||
                    (this.PairId != null &&
                    this.PairId.Equals(input.PairId))
                ) && 
                (
                    this.MakerOrderId == input.MakerOrderId ||
                    (this.MakerOrderId != null &&
                    this.MakerOrderId.Equals(input.MakerOrderId))
                ) && 
                (
                    this.TakerOrderId == input.TakerOrderId ||
                    (this.TakerOrderId != null &&
                    this.TakerOrderId.Equals(input.TakerOrderId))
                ) && 
                (
                    this.Price == input.Price ||
                    this.Price.Equals(input.Price)
                ) && 
                (
                    this.Amount == input.Amount ||
                    this.Amount.Equals(input.Amount)
                ) && 
                (
                    this.Total == input.Total ||
                    this.Total.Equals(input.Total)
                ) && 
                (
                    this.TransactionDate == input.TransactionDate ||
                    this.TransactionDate.Equals(input.TransactionDate)
                ) && 
                (
                    this.TradeType == input.TradeType ||
                    this.TradeType.Equals(input.TradeType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.PairId != null)
                    hashCode = hashCode * 59 + this.PairId.GetHashCode();
                if (this.MakerOrderId != null)
                    hashCode = hashCode * 59 + this.MakerOrderId.GetHashCode();
                if (this.TakerOrderId != null)
                    hashCode = hashCode * 59 + this.TakerOrderId.GetHashCode();
                hashCode = hashCode * 59 + this.Price.GetHashCode();
                hashCode = hashCode * 59 + this.Amount.GetHashCode();
                hashCode = hashCode * 59 + this.Total.GetHashCode();
                hashCode = hashCode * 59 + this.TransactionDate.GetHashCode();
                hashCode = hashCode * 59 + this.TradeType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
