/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines Type
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Type
    {
        /// <summary>
        /// Enum BtcBased for value: BtcBased
        /// </summary>
        [EnumMember(Value = "BtcBased")]
        BtcBased = 1,

        /// <summary>
        /// Enum EthBased for value: EthBased
        /// </summary>
        [EnumMember(Value = "EthBased")]
        EthBased = 2,

        /// <summary>
        /// Enum Fiat for value: Fiat
        /// </summary>
        [EnumMember(Value = "Fiat")]
        Fiat = 3,

        /// <summary>
        /// Enum Ripple for value: Ripple
        /// </summary>
        [EnumMember(Value = "Ripple")]
        Ripple = 4,

        /// <summary>
        /// Enum Eos for value: Eos
        /// </summary>
        [EnumMember(Value = "Eos")]
        Eos = 5,

        /// <summary>
        /// Enum ERC20 for value: ERC20
        /// </summary>
        [EnumMember(Value = "ERC20")]
        ERC20 = 6

    }

}
