/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ApplicationUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationUserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationUser
        //private ApplicationUser instance;

        public ApplicationUserTests()
        {
            // TODO uncomment below to create an instance of ApplicationUser
            //instance = new ApplicationUser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationUser
        /// </summary>
        [Fact]
        public void ApplicationUserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApplicationUser
            //Assert.IsInstanceOfType<ApplicationUser> (instance, "variable 'instance' is a ApplicationUser");
        }


        /// <summary>
        /// Test the property 'IsGoogleAuthenticatorEnabled'
        /// </summary>
        [Fact]
        public void IsGoogleAuthenticatorEnabledTest()
        {
            // TODO unit test for the property 'IsGoogleAuthenticatorEnabled'
        }
        /// <summary>
        /// Test the property 'GoogleAuthenticatorSecretKey'
        /// </summary>
        [Fact]
        public void GoogleAuthenticatorSecretKeyTest()
        {
            // TODO unit test for the property 'GoogleAuthenticatorSecretKey'
        }
        /// <summary>
        /// Test the property 'PinCode'
        /// </summary>
        [Fact]
        public void PinCodeTest()
        {
            // TODO unit test for the property 'PinCode'
        }
        /// <summary>
        /// Test the property 'LastIPAccess'
        /// </summary>
        [Fact]
        public void LastIPAccessTest()
        {
            // TODO unit test for the property 'LastIPAccess'
        }
        /// <summary>
        /// Test the property 'LastDateAccess'
        /// </summary>
        [Fact]
        public void LastDateAccessTest()
        {
            // TODO unit test for the property 'LastDateAccess'
        }
        /// <summary>
        /// Test the property 'IsChatDisabled'
        /// </summary>
        [Fact]
        public void IsChatDisabledTest()
        {
            // TODO unit test for the property 'IsChatDisabled'
        }
        /// <summary>
        /// Test the property 'MakerFee'
        /// </summary>
        [Fact]
        public void MakerFeeTest()
        {
            // TODO unit test for the property 'MakerFee'
        }
        /// <summary>
        /// Test the property 'TakerFee'
        /// </summary>
        [Fact]
        public void TakerFeeTest()
        {
            // TODO unit test for the property 'TakerFee'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'IsGoogleSignInAllowed'
        /// </summary>
        [Fact]
        public void IsGoogleSignInAllowedTest()
        {
            // TODO unit test for the property 'IsGoogleSignInAllowed'
        }
        /// <summary>
        /// Test the property 'IsFacebookSignInAllowed'
        /// </summary>
        [Fact]
        public void IsFacebookSignInAllowedTest()
        {
            // TODO unit test for the property 'IsFacebookSignInAllowed'
        }
        /// <summary>
        /// Test the property 'AffiliateUserId'
        /// </summary>
        [Fact]
        public void AffiliateUserIdTest()
        {
            // TODO unit test for the property 'AffiliateUserId'
        }
        /// <summary>
        /// Test the property 'RegistrationDateTime'
        /// </summary>
        [Fact]
        public void RegistrationDateTimeTest()
        {
            // TODO unit test for the property 'RegistrationDateTime'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'NormalizedUserName'
        /// </summary>
        [Fact]
        public void NormalizedUserNameTest()
        {
            // TODO unit test for the property 'NormalizedUserName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'NormalizedEmail'
        /// </summary>
        [Fact]
        public void NormalizedEmailTest()
        {
            // TODO unit test for the property 'NormalizedEmail'
        }
        /// <summary>
        /// Test the property 'EmailConfirmed'
        /// </summary>
        [Fact]
        public void EmailConfirmedTest()
        {
            // TODO unit test for the property 'EmailConfirmed'
        }
        /// <summary>
        /// Test the property 'PasswordHash'
        /// </summary>
        [Fact]
        public void PasswordHashTest()
        {
            // TODO unit test for the property 'PasswordHash'
        }
        /// <summary>
        /// Test the property 'SecurityStamp'
        /// </summary>
        [Fact]
        public void SecurityStampTest()
        {
            // TODO unit test for the property 'SecurityStamp'
        }
        /// <summary>
        /// Test the property 'ConcurrencyStamp'
        /// </summary>
        [Fact]
        public void ConcurrencyStampTest()
        {
            // TODO unit test for the property 'ConcurrencyStamp'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'PhoneNumberConfirmed'
        /// </summary>
        [Fact]
        public void PhoneNumberConfirmedTest()
        {
            // TODO unit test for the property 'PhoneNumberConfirmed'
        }
        /// <summary>
        /// Test the property 'TwoFactorEnabled'
        /// </summary>
        [Fact]
        public void TwoFactorEnabledTest()
        {
            // TODO unit test for the property 'TwoFactorEnabled'
        }
        /// <summary>
        /// Test the property 'LockoutEnd'
        /// </summary>
        [Fact]
        public void LockoutEndTest()
        {
            // TODO unit test for the property 'LockoutEnd'
        }
        /// <summary>
        /// Test the property 'LockoutEnabled'
        /// </summary>
        [Fact]
        public void LockoutEnabledTest()
        {
            // TODO unit test for the property 'LockoutEnabled'
        }
        /// <summary>
        /// Test the property 'AccessFailedCount'
        /// </summary>
        [Fact]
        public void AccessFailedCountTest()
        {
            // TODO unit test for the property 'AccessFailedCount'
        }

    }

}
