/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing BitcoinBasedCurrency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BitcoinBasedCurrencyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BitcoinBasedCurrency
        //private BitcoinBasedCurrency instance;

        public BitcoinBasedCurrencyTests()
        {
            // TODO uncomment below to create an instance of BitcoinBasedCurrency
            //instance = new BitcoinBasedCurrency();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BitcoinBasedCurrency
        /// </summary>
        [Fact]
        public void BitcoinBasedCurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BitcoinBasedCurrency
            //Assert.IsInstanceOfType<BitcoinBasedCurrency> (instance, "variable 'instance' is a BitcoinBasedCurrency");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Fact]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }
        /// <summary>
        /// Test the property 'RpcIp'
        /// </summary>
        [Fact]
        public void RpcIpTest()
        {
            // TODO unit test for the property 'RpcIp'
        }
        /// <summary>
        /// Test the property 'RpcPort'
        /// </summary>
        [Fact]
        public void RpcPortTest()
        {
            // TODO unit test for the property 'RpcPort'
        }
        /// <summary>
        /// Test the property 'RpcUsername'
        /// </summary>
        [Fact]
        public void RpcUsernameTest()
        {
            // TODO unit test for the property 'RpcUsername'
        }
        /// <summary>
        /// Test the property 'RpcPassword'
        /// </summary>
        [Fact]
        public void RpcPasswordTest()
        {
            // TODO unit test for the property 'RpcPassword'
        }

    }

}
