/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ChangeTracker
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChangeTrackerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChangeTracker
        //private ChangeTracker instance;

        public ChangeTrackerTests()
        {
            // TODO uncomment below to create an instance of ChangeTracker
            //instance = new ChangeTracker();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChangeTracker
        /// </summary>
        [Fact]
        public void ChangeTrackerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChangeTracker
            //Assert.IsInstanceOfType<ChangeTracker> (instance, "variable 'instance' is a ChangeTracker");
        }


        /// <summary>
        /// Test the property 'AutoDetectChangesEnabled'
        /// </summary>
        [Fact]
        public void AutoDetectChangesEnabledTest()
        {
            // TODO unit test for the property 'AutoDetectChangesEnabled'
        }
        /// <summary>
        /// Test the property 'LazyLoadingEnabled'
        /// </summary>
        [Fact]
        public void LazyLoadingEnabledTest()
        {
            // TODO unit test for the property 'LazyLoadingEnabled'
        }
        /// <summary>
        /// Test the property 'QueryTrackingBehavior'
        /// </summary>
        [Fact]
        public void QueryTrackingBehaviorTest()
        {
            // TODO unit test for the property 'QueryTrackingBehavior'
        }
        /// <summary>
        /// Test the property 'DeleteOrphansTiming'
        /// </summary>
        [Fact]
        public void DeleteOrphansTimingTest()
        {
            // TODO unit test for the property 'DeleteOrphansTiming'
        }
        /// <summary>
        /// Test the property 'CascadeDeleteTiming'
        /// </summary>
        [Fact]
        public void CascadeDeleteTimingTest()
        {
            // TODO unit test for the property 'CascadeDeleteTiming'
        }
        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

    }

}
