/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CryptoCurrency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CryptoCurrencyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CryptoCurrency
        //private CryptoCurrency instance;

        public CryptoCurrencyTests()
        {
            // TODO uncomment below to create an instance of CryptoCurrency
            //instance = new CryptoCurrency();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CryptoCurrency
        /// </summary>
        [Fact]
        public void CryptoCurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CryptoCurrency
            //Assert.IsInstanceOfType<CryptoCurrency> (instance, "variable 'instance' is a CryptoCurrency");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Fact]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }
        /// <summary>
        /// Test the property 'CurrencyType'
        /// </summary>
        [Fact]
        public void CurrencyTypeTest()
        {
            // TODO unit test for the property 'CurrencyType'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'DepositDisabled'
        /// </summary>
        [Fact]
        public void DepositDisabledTest()
        {
            // TODO unit test for the property 'DepositDisabled'
        }
        /// <summary>
        /// Test the property 'WithdrawDisabled'
        /// </summary>
        [Fact]
        public void WithdrawDisabledTest()
        {
            // TODO unit test for the property 'WithdrawDisabled'
        }
        /// <summary>
        /// Test the property 'CoinMarketCapId'
        /// </summary>
        [Fact]
        public void CoinMarketCapIdTest()
        {
            // TODO unit test for the property 'CoinMarketCapId'
        }
        /// <summary>
        /// Test the property 'CoinMarketCapUsdPrice'
        /// </summary>
        [Fact]
        public void CoinMarketCapUsdPriceTest()
        {
            // TODO unit test for the property 'CoinMarketCapUsdPrice'
        }
        /// <summary>
        /// Test the property 'CoinMarketCapLastUpdate'
        /// </summary>
        [Fact]
        public void CoinMarketCapLastUpdateTest()
        {
            // TODO unit test for the property 'CoinMarketCapLastUpdate'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'IsMarketCurrency'
        /// </summary>
        [Fact]
        public void IsMarketCurrencyTest()
        {
            // TODO unit test for the property 'IsMarketCurrency'
        }
        /// <summary>
        /// Test the property 'BlockExplolerTxIdUrl'
        /// </summary>
        [Fact]
        public void BlockExplolerTxIdUrlTest()
        {
            // TODO unit test for the property 'BlockExplolerTxIdUrl'
        }
        /// <summary>
        /// Test the property 'WithdrawCurrencyFee'
        /// </summary>
        [Fact]
        public void WithdrawCurrencyFeeTest()
        {
            // TODO unit test for the property 'WithdrawCurrencyFee'
        }
        /// <summary>
        /// Test the property 'WithdrawPercentFee'
        /// </summary>
        [Fact]
        public void WithdrawPercentFeeTest()
        {
            // TODO unit test for the property 'WithdrawPercentFee'
        }
        /// <summary>
        /// Test the property 'ConfirmationCount'
        /// </summary>
        [Fact]
        public void ConfirmationCountTest()
        {
            // TODO unit test for the property 'ConfirmationCount'
        }
        /// <summary>
        /// Test the property 'MinimumTradeAmount'
        /// </summary>
        [Fact]
        public void MinimumTradeAmountTest()
        {
            // TODO unit test for the property 'MinimumTradeAmount'
        }

    }

}
