/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DbContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DbContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DbContext
        //private DbContext instance;

        public DbContextTests()
        {
            // TODO uncomment below to create an instance of DbContext
            //instance = new DbContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DbContext
        /// </summary>
        [Fact]
        public void DbContextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DbContext
            //Assert.IsInstanceOfType<DbContext> (instance, "variable 'instance' is a DbContext");
        }


        /// <summary>
        /// Test the property 'Database'
        /// </summary>
        [Fact]
        public void DatabaseTest()
        {
            // TODO unit test for the property 'Database'
        }
        /// <summary>
        /// Test the property 'ChangeTracker'
        /// </summary>
        [Fact]
        public void ChangeTrackerTest()
        {
            // TODO unit test for the property 'ChangeTracker'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'ContextId'
        /// </summary>
        [Fact]
        public void ContextIdTest()
        {
            // TODO unit test for the property 'ContextId'
        }

    }

}
