/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing EnableDisable2Fa
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnableDisable2FaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnableDisable2Fa
        //private EnableDisable2Fa instance;

        public EnableDisable2FaTests()
        {
            // TODO uncomment below to create an instance of EnableDisable2Fa
            //instance = new EnableDisable2Fa();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnableDisable2Fa
        /// </summary>
        [Fact]
        public void EnableDisable2FaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnableDisable2Fa
            //Assert.IsInstanceOfType<EnableDisable2Fa> (instance, "variable 'instance' is a EnableDisable2Fa");
        }


        /// <summary>
        /// Test the property 'ClientCode'
        /// </summary>
        [Fact]
        public void ClientCodeTest()
        {
            // TODO unit test for the property 'ClientCode'
        }
        /// <summary>
        /// Test the property 'Pincode'
        /// </summary>
        [Fact]
        public void PincodeTest()
        {
            // TODO unit test for the property 'Pincode'
        }

    }

}
