/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ForgotPassword
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ForgotPasswordTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ForgotPassword
        //private ForgotPassword instance;

        public ForgotPasswordTests()
        {
            // TODO uncomment below to create an instance of ForgotPassword
            //instance = new ForgotPassword();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ForgotPassword
        /// </summary>
        [Fact]
        public void ForgotPasswordInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForgotPassword
            //Assert.IsInstanceOfType<ForgotPassword> (instance, "variable 'instance' is a ForgotPassword");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
