/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing IApplicationQrCommand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IApplicationQrCommandTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IApplicationQrCommand
        //private IApplicationQrCommand instance;

        public IApplicationQrCommandTests()
        {
            // TODO uncomment below to create an instance of IApplicationQrCommand
            //instance = new IApplicationQrCommand();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IApplicationQrCommand
        /// </summary>
        [Fact]
        public void IApplicationQrCommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IApplicationQrCommand
            //Assert.IsInstanceOfType<IApplicationQrCommand> (instance, "variable 'instance' is a IApplicationQrCommand");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'QrCommand'
        /// </summary>
        [Fact]
        public void QrCommandTest()
        {
            // TODO unit test for the property 'QrCommand'
        }
        /// <summary>
        /// Test the property 'Executed'
        /// </summary>
        [Fact]
        public void ExecutedTest()
        {
            // TODO unit test for the property 'Executed'
        }

    }

}
