/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing IApplicationTokenAccess
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IApplicationTokenAccessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IApplicationTokenAccess
        //private IApplicationTokenAccess instance;

        public IApplicationTokenAccessTests()
        {
            // TODO uncomment below to create an instance of IApplicationTokenAccess
            //instance = new IApplicationTokenAccess();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IApplicationTokenAccess
        /// </summary>
        [Fact]
        public void IApplicationTokenAccessInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IApplicationTokenAccess
            //Assert.IsInstanceOfType<IApplicationTokenAccess> (instance, "variable 'instance' is a IApplicationTokenAccess");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'TokenString'
        /// </summary>
        [Fact]
        public void TokenStringTest()
        {
            // TODO unit test for the property 'TokenString'
        }
        /// <summary>
        /// Test the property 'DeviceDescription'
        /// </summary>
        [Fact]
        public void DeviceDescriptionTest()
        {
            // TODO unit test for the property 'DeviceDescription'
        }
        /// <summary>
        /// Test the property 'DevicePushToken'
        /// </summary>
        [Fact]
        public void DevicePushTokenTest()
        {
            // TODO unit test for the property 'DevicePushToken'
        }
        /// <summary>
        /// Test the property 'Expiry'
        /// </summary>
        [Fact]
        public void ExpiryTest()
        {
            // TODO unit test for the property 'Expiry'
        }
        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }

    }

}
