/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing IdentityRole
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityRoleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityRole
        //private IdentityRole instance;

        public IdentityRoleTests()
        {
            // TODO uncomment below to create an instance of IdentityRole
            //instance = new IdentityRole();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityRole
        /// </summary>
        [Fact]
        public void IdentityRoleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IdentityRole
            //Assert.IsInstanceOfType<IdentityRole> (instance, "variable 'instance' is a IdentityRole");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NormalizedName'
        /// </summary>
        [Fact]
        public void NormalizedNameTest()
        {
            // TODO unit test for the property 'NormalizedName'
        }
        /// <summary>
        /// Test the property 'ConcurrencyStamp'
        /// </summary>
        [Fact]
        public void ConcurrencyStampTest()
        {
            // TODO unit test for the property 'ConcurrencyStamp'
        }

    }

}
