/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Order
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Order
        //private Order instance;

        public OrderTests()
        {
            // TODO uncomment below to create an instance of Order
            //instance = new Order();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Order
        /// </summary>
        [Fact]
        public void OrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Order
            //Assert.IsInstanceOfType<Order> (instance, "variable 'instance' is a Order");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'TradeType'
        /// </summary>
        [Fact]
        public void TradeTypeTest()
        {
            // TODO unit test for the property 'TradeType'
        }
        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Fact]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }
        /// <summary>
        /// Test the property 'OrderState'
        /// </summary>
        [Fact]
        public void OrderStateTest()
        {
            // TODO unit test for the property 'OrderState'
        }
        /// <summary>
        /// Test the property 'TradePairId'
        /// </summary>
        [Fact]
        public void TradePairIdTest()
        {
            // TODO unit test for the property 'TradePairId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'AmountLeft'
        /// </summary>
        [Fact]
        public void AmountLeftTest()
        {
            // TODO unit test for the property 'AmountLeft'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'TotalLeft'
        /// </summary>
        [Fact]
        public void TotalLeftTest()
        {
            // TODO unit test for the property 'TotalLeft'
        }
        /// <summary>
        /// Test the property 'StopLossPrice'
        /// </summary>
        [Fact]
        public void StopLossPriceTest()
        {
            // TODO unit test for the property 'StopLossPrice'
        }
        /// <summary>
        /// Test the property 'TakeProfitPrice'
        /// </summary>
        [Fact]
        public void TakeProfitPriceTest()
        {
            // TODO unit test for the property 'TakeProfitPrice'
        }
        /// <summary>
        /// Test the property 'IsMargin'
        /// </summary>
        [Fact]
        public void IsMarginTest()
        {
            // TODO unit test for the property 'IsMargin'
        }
        /// <summary>
        /// Test the property 'LiquidationPrice'
        /// </summary>
        [Fact]
        public void LiquidationPriceTest()
        {
            // TODO unit test for the property 'LiquidationPrice'
        }
        /// <summary>
        /// Test the property 'InitialPrice'
        /// </summary>
        [Fact]
        public void InitialPriceTest()
        {
            // TODO unit test for the property 'InitialPrice'
        }
        /// <summary>
        /// Test the property 'Leverage'
        /// </summary>
        [Fact]
        public void LeverageTest()
        {
            // TODO unit test for the property 'Leverage'
        }
        /// <summary>
        /// Test the property 'InitialAmount'
        /// </summary>
        [Fact]
        public void InitialAmountTest()
        {
            // TODO unit test for the property 'InitialAmount'
        }
        /// <summary>
        /// Test the property 'PairCurrencyId'
        /// </summary>
        [Fact]
        public void PairCurrencyIdTest()
        {
            // TODO unit test for the property 'PairCurrencyId'
        }
        /// <summary>
        /// Test the property 'MarketCurrencyId'
        /// </summary>
        [Fact]
        public void MarketCurrencyIdTest()
        {
            // TODO unit test for the property 'MarketCurrencyId'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Fact]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'DateClosed'
        /// </summary>
        [Fact]
        public void DateClosedTest()
        {
            // TODO unit test for the property 'DateClosed'
        }
        /// <summary>
        /// Test the property 'DateOnMarket'
        /// </summary>
        [Fact]
        public void DateOnMarketTest()
        {
            // TODO unit test for the property 'DateOnMarket'
        }
        /// <summary>
        /// Test the property 'Closed'
        /// </summary>
        [Fact]
        public void ClosedTest()
        {
            // TODO unit test for the property 'Closed'
        }
        /// <summary>
        /// Test the property 'ConcurrencyStamp'
        /// </summary>
        [Fact]
        public void ConcurrencyStampTest()
        {
            // TODO unit test for the property 'ConcurrencyStamp'
        }

    }

}
