/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OrderState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderState
        //private OrderState instance;

        public OrderStateTests()
        {
            // TODO uncomment below to create an instance of OrderState
            //instance = new OrderState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderState
        /// </summary>
        [Fact]
        public void OrderStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderState
            //Assert.IsInstanceOfType<OrderState> (instance, "variable 'instance' is a OrderState");
        }



    }

}
