/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PostGetReferrerEmailRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostGetReferrerEmailRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostGetReferrerEmailRequest
        //private PostGetReferrerEmailRequest instance;

        public PostGetReferrerEmailRequestTests()
        {
            // TODO uncomment below to create an instance of PostGetReferrerEmailRequest
            //instance = new PostGetReferrerEmailRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostGetReferrerEmailRequest
        /// </summary>
        [Fact]
        public void PostGetReferrerEmailRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostGetReferrerEmailRequest
            //Assert.IsInstanceOfType<PostGetReferrerEmailRequest> (instance, "variable 'instance' is a PostGetReferrerEmailRequest");
        }


        /// <summary>
        /// Test the property 'RefId'
        /// </summary>
        [Fact]
        public void RefIdTest()
        {
            // TODO unit test for the property 'RefId'
        }

    }

}
