/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PostSetAffiliateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostSetAffiliateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostSetAffiliateRequest
        //private PostSetAffiliateRequest instance;

        public PostSetAffiliateRequestTests()
        {
            // TODO uncomment below to create an instance of PostSetAffiliateRequest
            //instance = new PostSetAffiliateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostSetAffiliateRequest
        /// </summary>
        [Fact]
        public void PostSetAffiliateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostSetAffiliateRequest
            //Assert.IsInstanceOfType<PostSetAffiliateRequest> (instance, "variable 'instance' is a PostSetAffiliateRequest");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

    }

}
