/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PostSendSms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostSendSmsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostSendSms
        //private PostSendSms instance;

        public PostSendSmsTests()
        {
            // TODO uncomment below to create an instance of PostSendSms
            //instance = new PostSendSms();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostSendSms
        /// </summary>
        [Fact]
        public void PostSendSmsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostSendSms
            //Assert.IsInstanceOfType<PostSendSms> (instance, "variable 'instance' is a PostSendSms");
        }


        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

    }

}
