/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PostWithdrawRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostWithdrawRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostWithdrawRequest
        //private PostWithdrawRequest instance;

        public PostWithdrawRequestTests()
        {
            // TODO uncomment below to create an instance of PostWithdrawRequest
            //instance = new PostWithdrawRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostWithdrawRequest
        /// </summary>
        [Fact]
        public void PostWithdrawRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostWithdrawRequest
            //Assert.IsInstanceOfType<PostWithdrawRequest> (instance, "variable 'instance' is a PostWithdrawRequest");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PinCode'
        /// </summary>
        [Fact]
        public void PinCodeTest()
        {
            // TODO unit test for the property 'PinCode'
        }
        /// <summary>
        /// Test the property 'DestinationTag'
        /// </summary>
        [Fact]
        public void DestinationTagTest()
        {
            // TODO unit test for the property 'DestinationTag'
        }
        /// <summary>
        /// Test the property 'TwoFactorCode'
        /// </summary>
        [Fact]
        public void TwoFactorCodeTest()
        {
            // TODO unit test for the property 'TwoFactorCode'
        }

    }

}
