/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PostOrdersRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostOrdersRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostOrdersRequest
        //private PostOrdersRequest instance;

        public PostOrdersRequestTests()
        {
            // TODO uncomment below to create an instance of PostOrdersRequest
            //instance = new PostOrdersRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostOrdersRequest
        /// </summary>
        [Fact]
        public void PostOrdersRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostOrdersRequest
            //Assert.IsInstanceOfType<PostOrdersRequest> (instance, "variable 'instance' is a PostOrdersRequest");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'TradeType'
        /// </summary>
        [Fact]
        public void TradeTypeTest()
        {
            // TODO unit test for the property 'TradeType'
        }
        /// <summary>
        /// Test the property 'PairId'
        /// </summary>
        [Fact]
        public void PairIdTest()
        {
            // TODO unit test for the property 'PairId'
        }
        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Fact]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
