/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Quote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuoteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Quote
        //private Quote instance;

        public QuoteTests()
        {
            // TODO uncomment below to create an instance of Quote
            //instance = new Quote();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Quote
        /// </summary>
        [Fact]
        public void QuoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Quote
            //Assert.IsInstanceOfType<Quote> (instance, "variable 'instance' is a Quote");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PairId'
        /// </summary>
        [Fact]
        public void PairIdTest()
        {
            // TODO unit test for the property 'PairId'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Open'
        /// </summary>
        [Fact]
        public void OpenTest()
        {
            // TODO unit test for the property 'Open'
        }
        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Fact]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }
        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Fact]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }
        /// <summary>
        /// Test the property 'Close'
        /// </summary>
        [Fact]
        public void CloseTest()
        {
            // TODO unit test for the property 'Close'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Fact]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
        /// <summary>
        /// Test the property 'PairVolume'
        /// </summary>
        [Fact]
        public void PairVolumeTest()
        {
            // TODO unit test for the property 'PairVolume'
        }

    }

}
