/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SignUp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignUpTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignUp
        //private SignUp instance;

        public SignUpTests()
        {
            // TODO uncomment below to create an instance of SignUp
            //instance = new SignUp();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignUp
        /// </summary>
        [Fact]
        public void SignUpInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignUp
            //Assert.IsInstanceOfType<SignUp> (instance, "variable 'instance' is a SignUp");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'PinCode'
        /// </summary>
        [Fact]
        public void PinCodeTest()
        {
            // TODO unit test for the property 'PinCode'
        }
        /// <summary>
        /// Test the property 'IsInApp'
        /// </summary>
        [Fact]
        public void IsInAppTest()
        {
            // TODO unit test for the property 'IsInApp'
        }

    }

}
