/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SmsVerificationMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SmsVerificationMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SmsVerificationMessage
        //private SmsVerificationMessage instance;

        public SmsVerificationMessageTests()
        {
            // TODO uncomment below to create an instance of SmsVerificationMessage
            //instance = new SmsVerificationMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SmsVerificationMessage
        /// </summary>
        [Fact]
        public void SmsVerificationMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SmsVerificationMessage
            //Assert.IsInstanceOfType<SmsVerificationMessage> (instance, "variable 'instance' is a SmsVerificationMessage");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'LastSendTime'
        /// </summary>
        [Fact]
        public void LastSendTimeTest()
        {
            // TODO unit test for the property 'LastSendTime'
        }

    }

}
