/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StringIdentityUserRole
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StringIdentityUserRoleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StringIdentityUserRole
        //private StringIdentityUserRole instance;

        public StringIdentityUserRoleTests()
        {
            // TODO uncomment below to create an instance of StringIdentityUserRole
            //instance = new StringIdentityUserRole();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StringIdentityUserRole
        /// </summary>
        [Fact]
        public void StringIdentityUserRoleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StringIdentityUserRole
            //Assert.IsInstanceOfType<StringIdentityUserRole> (instance, "variable 'instance' is a StringIdentityUserRole");
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'RoleId'
        /// </summary>
        [Fact]
        public void RoleIdTest()
        {
            // TODO unit test for the property 'RoleId'
        }

    }

}
