/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StringIdentityUserToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StringIdentityUserTokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StringIdentityUserToken
        //private StringIdentityUserToken instance;

        public StringIdentityUserTokenTests()
        {
            // TODO uncomment below to create an instance of StringIdentityUserToken
            //instance = new StringIdentityUserToken();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StringIdentityUserToken
        /// </summary>
        [Fact]
        public void StringIdentityUserTokenInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StringIdentityUserToken
            //Assert.IsInstanceOfType<StringIdentityUserToken> (instance, "variable 'instance' is a StringIdentityUserToken");
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'LoginProvider'
        /// </summary>
        [Fact]
        public void LoginProviderTest()
        {
            // TODO unit test for the property 'LoginProvider'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
