/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StringIdentityUserClaim
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StringIdentityUserClaimTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StringIdentityUserClaim
        //private StringIdentityUserClaim instance;

        public StringIdentityUserClaimTests()
        {
            // TODO uncomment below to create an instance of StringIdentityUserClaim
            //instance = new StringIdentityUserClaim();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StringIdentityUserClaim
        /// </summary>
        [Fact]
        public void StringIdentityUserClaimInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StringIdentityUserClaim
            //Assert.IsInstanceOfType<StringIdentityUserClaim> (instance, "variable 'instance' is a StringIdentityUserClaim");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'ClaimType'
        /// </summary>
        [Fact]
        public void ClaimTypeTest()
        {
            // TODO unit test for the property 'ClaimType'
        }
        /// <summary>
        /// Test the property 'ClaimValue'
        /// </summary>
        [Fact]
        public void ClaimValueTest()
        {
            // TODO unit test for the property 'ClaimValue'
        }

    }

}
