/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StringIdentityRoleClaim
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StringIdentityRoleClaimTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StringIdentityRoleClaim
        //private StringIdentityRoleClaim instance;

        public StringIdentityRoleClaimTests()
        {
            // TODO uncomment below to create an instance of StringIdentityRoleClaim
            //instance = new StringIdentityRoleClaim();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StringIdentityRoleClaim
        /// </summary>
        [Fact]
        public void StringIdentityRoleClaimInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StringIdentityRoleClaim
            //Assert.IsInstanceOfType<StringIdentityRoleClaim> (instance, "variable 'instance' is a StringIdentityRoleClaim");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RoleId'
        /// </summary>
        [Fact]
        public void RoleIdTest()
        {
            // TODO unit test for the property 'RoleId'
        }
        /// <summary>
        /// Test the property 'ClaimType'
        /// </summary>
        [Fact]
        public void ClaimTypeTest()
        {
            // TODO unit test for the property 'ClaimType'
        }
        /// <summary>
        /// Test the property 'ClaimValue'
        /// </summary>
        [Fact]
        public void ClaimValueTest()
        {
            // TODO unit test for the property 'ClaimValue'
        }

    }

}
