/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TradingAmount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TradingAmountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TradingAmount
        //private TradingAmount instance;

        public TradingAmountTests()
        {
            // TODO uncomment below to create an instance of TradingAmount
            //instance = new TradingAmount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TradingAmount
        /// </summary>
        [Fact]
        public void TradingAmountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TradingAmount
            //Assert.IsInstanceOfType<TradingAmount> (instance, "variable 'instance' is a TradingAmount");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'TotalBtc'
        /// </summary>
        [Fact]
        public void TotalBtcTest()
        {
            // TODO unit test for the property 'TotalBtc'
        }
        /// <summary>
        /// Test the property 'MonthBtc'
        /// </summary>
        [Fact]
        public void MonthBtcTest()
        {
            // TODO unit test for the property 'MonthBtc'
        }
        /// <summary>
        /// Test the property 'PromoPeriodBtc'
        /// </summary>
        [Fact]
        public void PromoPeriodBtcTest()
        {
            // TODO unit test for the property 'PromoPeriodBtc'
        }

    }

}
