/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing UserCategory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserCategoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserCategory
        //private UserCategory instance;

        public UserCategoryTests()
        {
            // TODO uncomment below to create an instance of UserCategory
            //instance = new UserCategory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserCategory
        /// </summary>
        [Fact]
        public void UserCategoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserCategory
            //Assert.IsInstanceOfType<UserCategory> (instance, "variable 'instance' is a UserCategory");
        }



    }

}
