/* 
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing WithdrawRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WithdrawRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WithdrawRequest
        //private WithdrawRequest instance;

        public WithdrawRequestTests()
        {
            // TODO uncomment below to create an instance of WithdrawRequest
            //instance = new WithdrawRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WithdrawRequest
        /// </summary>
        [Fact]
        public void WithdrawRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WithdrawRequest
            //Assert.IsInstanceOfType<WithdrawRequest> (instance, "variable 'instance' is a WithdrawRequest");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Fact]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Fact]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'Paid'
        /// </summary>
        [Fact]
        public void PaidTest()
        {
            // TODO unit test for the property 'Paid'
        }
        /// <summary>
        /// Test the property 'DatePaid'
        /// </summary>
        [Fact]
        public void DatePaidTest()
        {
            // TODO unit test for the property 'DatePaid'
        }
        /// <summary>
        /// Test the property 'TxId'
        /// </summary>
        [Fact]
        public void TxIdTest()
        {
            // TODO unit test for the property 'TxId'
        }
        /// <summary>
        /// Test the property 'DestinationAddress'
        /// </summary>
        [Fact]
        public void DestinationAddressTest()
        {
            // TODO unit test for the property 'DestinationAddress'
        }
        /// <summary>
        /// Test the property 'DestinationTag'
        /// </summary>
        [Fact]
        public void DestinationTagTest()
        {
            // TODO unit test for the property 'DestinationTag'
        }

    }

}
